### ISSUE TITLE
Questions about parameter updates

### ISSUE THREAD

**Issue by wnma3mz** [wuch15/FedKD#1]
Thanks to the author for making the code open source. But there are some details about the code that I don't quite understand.

1. `latest_local_student_para`, which is not the latest parameter, seems to have been assigned at the beginning and not updated.

https://github.com/wuch15/FedKD/blob/6166696e4abd74a16c2d7d80aa7983b99c17e153/run.py#L131

2. The aggregate parameter is `student_update`. The gradient is the difference between the latest weight parameter and the previous weight parameter. But when update a local model parameter, this code replace it directly, right? (Could the gradient be replaced directly with a weight value?)

https://github.com/wuch15/FedKD/blob/6166696e4abd74a16c2d7d80aa7983b99c17e153/run.py#L188

https://github.com/wuch15/FedKD/blob/6166696e4abd74a16c2d7d80aa7983b99c17e153/run.py#L246

I'm looking forward to your reply.

**Comment by wuch15** [comment]
Hi,
Thanks for creating the first issue! It is indeed a bug that may be introduced by code re-org. It seems that an update of this variable is missing and I added it to the end of the loop. The gradient should be added to the original local model parameters and I have corrected this issue in the file.

**Comment by wnma3mz** [comment]
Great job! I would like to ask one more question, does the value of `energy` have a big impact on the results if it is kept constant? For example, a fixed value of `0.95`.

**Comment by wuch15** [comment]
Hi, I think this depends on the difficulty of the task. If the task is hard may be a high and dynamic energy threshold is required. If the task is not so challenging, a fixed and even lower threshold can be used and there is no big performance loss (I tried it on some very easy tasks such as MNIST, though not reported in the article).

**Comment by wnma3mz** [comment]
> Hi, I think this depends on the difficulty of the task. If the task is hard may be a high and dynamic energy threshold is required. If the task is not so challenging, a fixed and even lower threshold can be used and there is no big performance loss (I tried it on some very easy tasks such as MNIST, though not reported in the article).

Thank you for your reply! It saves me a lot of time.

**Comment by xiaoSUM** [comment]
> > Hi, I think this depends on the difficulty of the task. If the task is hard may be a high and dynamic energy threshold is required. If the task is not so challenging, a fixed and even lower threshold can be used and there is no big performance loss (I tried it on some very easy tasks such as MNIST, though not reported in the article).
> 
> Thank you for your reply! It saves me a lot of time.

Hi,have you used the open source model bert and other running through the project, can you share your model to use which?I'm looking forward to your reply,thank you!
